name = "HSVIforOSPOSGs"
uuid = "28136be4-687d-4786-8c85-223b052e0651"
authors = ["Jakub Bro≈æ <brozjak2@fel.cvut.cz>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
