name = "HSVIforOSPOSGs"
uuid = "28136be4-687d-4786-8c85-223b052e0651"
authors = ["Jakub Bro≈æ <brozjak2@fel.cvut.cz>"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
